services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - default_network
    depends_on:
      db-init:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    volumes:
      - ./migrations:/app/migrations

  db-init:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m projeto_aplicado.scripts.init_db
    env_file:
      - .env
    networks:
      - default_network
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - default_network

  redis:
    image: redis:7.4.2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - default_network

volumes:
  postgres_data:
  redis_data:

networks:
  default_network:
